# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# Inherits from tesser-payments/coderabbit.
# See https://github.com/tesser-payments/coderabbit/blob/main/README.md
inheritance: true
